export const CAR_MODELS: { [key: string]: string[] } = {
    Audi: [
        'A3',
        'A4',
        'A5',
        'A6',
        'A7',
        'A8',
        'Q2',
        'Q3',
        'Q4 e-tron',
        'Q5',
        'Q7',
        'Q8',
        'R8',
        'TT',
        'e-tron',
    ],
    BMW: [
        '1 Series',
        '2 Series',
        '3 Series',
        '4 Series',
        '5 Series',
        '6 Series',
        '7 Series',
        '8 Series',
        'i3',
        'i4',
        'i8',
        'X1',
        'X2',
        'X3',
        'X4',
        'X5',
        'X6',
        'X7',
        'Z4',
    ],
    Chevrolet: [
        'Blazer',
        'Bolt EV',
        'Camaro',
        'Colorado',
        'Corvette',
        'Equinox',
        'Impala',
        'Malibu',
        'Silverado',
        'Spark',
        'Suburban',
        'Tahoe',
        'Traverse',
        'Trax',
        'Volt',
    ],
    Citroen: [
        'Berlingo',
        'C1',
        'C3',
        'C3 Aircross',
        'C3 Picasso',
        'C4',
        'C4 Cactus',
        'C4 Picasso',
        'C5 Aircross',
        'Grand C4 SpaceTourer',
    ],
    Fiat: [
        '124 Spider',
        '500',
        '500L',
        '500X',
        'Ducato',
        'Fiorino',
        'Panda',
        'Punto',
        'Qubo',
        'Tipo',
    ],
    Ford: [
        'Bronco',
        'EcoSport',
        'Edge',
        'Escape',
        'Expedition',
        'Explorer',
        'F-150',
        'Flex',
        'Focus',
        'Fusion',
        'Mustang',
        'Ranger',
        'Transit',
    ],
    Honda: [
        'Accord',
        'Civic',
        'CR-V',
        'Crosstour',
        'Element',
        'Fit',
        'HR-V',
        'Insight',
        'Odyssey',
        'Passport',
        'Pilot',
        'Ridgeline',
    ],
    Hyundai: [
        'Accent',
        'Elantra',
        'Ioniq',
        'Kona',
        'Palisade',
        'Santa Fe',
        'Sonata',
        'Tucson',
        'Veloster',
        'Venue',
    ],
    Kia: [
        'Carnival',
        'Forte',
        'K5',
        'Niro',
        'Optima',
        'Rio',
        'Seltos',
        'Sorento',
        'Soul',
        'Sportage',
        'Stinger',
        'Telluride',
    ],
    'Mercedes-Benz': [
        'A-Class',
        'B-Class',
        'C-Class',
        'CLA',
        'CLS',
        'E-Class',
        'G-Class',
        'GLA',
        'GLB',
        'GLC',
        'GLE',
        'GLS',
        'S-Class',
        'SLC',
    ],
    Nissan: [
        'Altima',
        'Armada',
        'Frontier',
        'GT-R',
        'Juke',
        'Kicks',
        'Leaf',
        'Maxima',
        'Murano',
        'Pathfinder',
        'Qashqai',
        'Rogue',
        'Sentra',
        'Titan',
        'Versa',
    ],
    Peugeot: [
        '108',
        '2008',
        '208',
        '3008',
        '308',
        '5008',
        '508',
        'Rifter',
        'Traveller',
    ],
    Renault: [
        'Arkana',
        'Captur',
        'Clio',
        'Espace',
        'Kadjar',
        'Koleos',
        'Megane',
        'Scenic',
        'Talisman',
        'Zoe',
    ],
    Skoda: [
        'Citigo',
        'Enyaq',
        'Fabia',
        'Kamiq',
        'Karoq',
        'Kodiaq',
        'Octavia',
        'Rapid',
        'Scala',
        'Superb',
    ],
    Tesla: [
        'Cybertruck',
        'Model 3',
        'Model S',
        'Model S Plaid',
        'Model X',
        'Model Y',
        'Roadster',
    ],
    Toyota: [
        '4Runner',
        'Avalon',
        'C-HR',
        'Camry',
        'Corolla',
        'Highlander',
        'Land Cruiser',
        'Prius',
        'RAV4',
        'Sienna',
        'Supra',
        'Tacoma',
        'Tundra',
        'Yaris',
    ],
    Volkswagen: [
        'Arteon',
        'Atlas',
        'Beetle',
        'Golf',
        'Golf GTI',
        'ID.3',
        'ID.4',
        'Jetta',
        'Passat',
        'Polo',
        'T-Cross',
        'T-Roc',
        'Tiguan',
        'Touareg',
        'e-Golf',
    ],
    Volvo: ['S60', 'S90', 'V40', 'V60', 'V90', 'XC40', 'XC60', 'XC90'],
};
