export const REPARATION_TYPES = [
    'Transmission Repair',
    'Brake Service',
    'Exhaust System Repair',
    'Suspension and Steering Repair',
    'Electrical System Service',
    'Heating and Air Conditioning Service',
    'Oil, Lube, and Filter Service',
    'Battery Replacement and Service',
    'Wheel Alignment',
    'Tire Repair and Replacement',
    'Cooling System Service',
    'Fuel System Maintenance',
    'Engine Diagnostics and Performance',
    'Windshield and Glass Repair',
    'Interior Repair (such as upholstery and electronics)',
    'Detailing Services',
    'Safety and Emissions Inspections',
    'Hybrid and Electric Vehicle Service',
    'Performance Upgrades',
    'Preventive Maintenance Checks',
];
