export enum Endpoints {
    LOGIN = 'Authentication/login',
    REGISTER = 'Authentication/register',
    GET_LOGGED_USER = 'Authentication',
    GET_USERS = 'User',
    PUT_USER = 'User',
    MECHANICS = 'User/Mechanics',
    GET_MECHANIC_REPARATIONS = 'Reparation/Mechanic',
    GET_REPARATION = 'Reparation',
    POST_REPARATION = 'Reparation',
    PUT_REPARATION = 'Reparation',
    DELETE_REPARATION = 'Reparation',
    GET_CARS = 'Car',
    POST_CAR = 'Car',
    PUT_CAR = 'Car',
    DELETE_CAR = 'Car',
    GET_BILL = 'Bill',
    POST_BILL = 'Bill',
}
